<?php

namespace App\Entity\Misc;

use App\Entity\Misc\ArchivableTrait;
use DateTime;
use Exception;

class GeneralCode
{   
    use ArchivableTrait;
    #CORE
    const CATEGORY_SSA = 'RUC_CMPN_3';
    const CATEGORY_SIC = 'RGC_SC';
    const CATEGORY_SECTOR_FRAMEWORK = 'PGC_SECTOR_FRAMEWORK';
    const CATEGORY_LEVY_CATEGORY = 'RUC_CMPN_1';
    const CATEGORY_ML1 = 'RGC_M1';
    const CATEGORY_ML2 = 'RGC_M2';
    const CATEGORY_RELATIONSHIP = 'RGC_RP';
    const CATEGORY_MODE_OF_ATTENDANCE = 'RGC_MO';
    const CATEGORY_LOCATION = 'RCC_COLLEGE_CENTRE';
    const CATEGORY_VENUE = 'RSV';
    #BP
    const CATEGORY_BP_MODE_OF_STUDY = 'PGC_BP_MODE_OF_STUDY';
    const CATEGORY_BP_FEE_TYPE = 'PGC_BP_FEE_TYPE';
    const CATEGORY_BP_PROGRAMME_STATUS = 'PGC_BP_PROG_STATUS';
    #ORG
    const CATEGORY_ORG_SIZE = 'RGC_ETE';
    const CATEGORY_ORG_STATUS = 'RGC_CST';
    const CATEGORY_ORG_RATING = 'RUC_CMPN_2';
    #WES
    const CATEGORY_WES_WHO_PAYS_FEES = 'PGC_WES_WHO_PAYS_FEES';
    const CATEGORY_WES_PAYMENT_METHOD = 'PGC_WES_PAYMENT_METHOD';
    const CATEGORY_WES_GENERATED_BY = 'PGC_WES_GENERATED_BY';
    const CATEGORY_WES_RELATIONSHIP = 'PGC_WES_RELATIONSHIP';
    const CATEGORY_WES_DISABILITY = 'PGC_WES_DISABILITY';
    const CATEGORY_WES_PRIMARY_SUPPORT_NEED = 'PGC_WES_PRIMARY_SUPPORT_NEED';
    const CATEGORY_WES_ETHNICITY = 'PGC_WES_ETHNICITY';
    const CATEGORY_WES_PRIOR_ATTAINMENT_LEVEL = 'PGC_WES_PRIOR_ATTAINMENT_LEVEL';
    const CATEGORY_WES_HOUSEHOLD_SITUATION = 'PGC_WES_HOUSEHOLD_SITUATION';
    const CATEGORY_WES_EMPLOYMENT_STATUS = 'PGC_WES_EMPLOYMENT_STATUS';
    const CATEGORY_WES_EMPLOYMENT_LENGTH = 'PGC_WES_EMPLOYMENT_LENGTH';
    const CATEGORY_WES_UNEMPLOYMENT_LENGTH = 'PGC_WES_UNEMPLOYMENT_LENGTH';
    const CATEGORY_WES_BENEFIT_STATUS = 'PGC_WES_BENEFIT_STATUS';
    const CATEGORY_WES_EMPLOYER_SIZE = 'PGC_WES_EMPLOYER_SIZE';
    const CATEGORY_WES_FEEDBACK = 'PGC_WES_FEEDBACK';
    const CATEGORY_WES_HIGHEST_QUALIFICATION = 'PGC_WES_HIGHEST_QUALIFICATION';
    const CATEGORY_WES_NATIONALITY = 'PGC_WES_NATIONALITY';    
    const CATEGORY_WES_COUNTRY = 'PGC_WES_COUNTRY';
    const CATEGORY_WES_FEE_REMISSION_GROUP = 'PGC_WES_FEE_REMISSION_GROUP';
    const CATEGORY_WES_FEE_REMISSION_CATEGORY = 'PGC_WES_FEE_REMISSION_CATEGORY';
    const CATEGORY_WES_ENROLMENT_STATUS = 'PGC_WES_ENROLMENT_STATUS';
    const CATEGORY_WES_ENROLMENT_PROCESS = 'PGC_WES_ENROLMENT_PROCESS';
    const CATEGORY_WES_ENROLMENT_TRACKER = 'PGC_WES_ENROLMENT_TRACKER';
    #CRM
    const CATEGORY_CRM_CHECK = 'PGC_CRM_CHECK';
    #STAFF
    const CATEGORY_STAFF_APPRAISAL_STATUS = 'PGC_STAFF_APPRAISAL_STATUS';
    const CATEGORY_STAFF_APPRAISAL_RATING= 'PGC_STAFF_APPRAISAL_RATING';
    const CATEGORY_STAFF_APPRAISAL_CATEGORY = 'RUC_PERS_1';
    const CATEGORY_STAFF_EMPLOYEE_TYPE = 'RUC_PERS_2';
    const CATEGORY_STAFF_APPRAISAL_TARGET_STATUS = 'PGC_STAFF_APPRAISAL_TARGET_STATUS';
    const CATEGORY_STAFF_STRATEGIC_PRIORITY = 'PGC_STAFF_STRATEGIC_PRIORITY';
    const CATEGORY_STAFF_OBSERVATION_LEARNER_CATEGORY = 'PGC_STAFF_OBSERVATION_LEARNER_CATEGORY';
    const CATEGORY_STAFF_OBSERVATION_NUMBER = 'PGC_STAFF_OBSERVATION_NUMBER';
    const CATEGORY_STAFF_OBSERVATION_COURSE_LEVEL = 'PGC_STAFF_OBSERVATION_COURSE_LEVEL';
    const CATEGORY_STAFF_OBSERVATION_GRADE = 'PGC_STAFF_OBSERVATION_GRADE';
    const CATEGORY_STAFF_DEVELOPMENT_APPLICATION_STATUS = 'PGC_STAFF_DEVELOPMENT_APPLICATION_STATUS';
    const CATEGORY_STAFF_DEVELOPMENT_APPLICATION_PRIORITY = 'PGC_STAFF_DEVELOPMENT_APPLICATION_PRIORITY';
    #STUDENT
    const CATEGORY_STUDENT_DIRECTED_SELF_STUDY_TYPE = 'PGC_STUDENT_DIRECTED_SELF_STUDY_TYPE';
    const CATEGORY_STUDENT_WORK_EXPERIENCE_STATUS = 'PGC_STUDENT_WORK_EXPERIENCE_STATUS';
    const CATEGORY_STUDENT_DLSF_BENEFIT_TYPE = 'PGC_DLSF_BENEFIT_TYPE';
    const CATEGORY_STUDENT_DLSF_AGE_CATEGORY = 'PGC_DLSF_AGE_CATEGORY';
    const CATEGORY_STUDENT_QUALIFICATION_GRADE = 'PGC_STUDENT_QUALIFICATION_GRADE';
    const CATEGORY_STUDENT_QUALIFICATION_SUBJECT_CATEGORY = 'PGC_STUDENT_QUALIFICATION_SUBJECT_CATEGORY';
    const CATEGORY_STUDENT_COUNTRY_OF_DOMICILE = 'RIC_COD';
    const CATEGORY_STUDENT_HEALTH_WELLBEING = 'RGC_HAW';
    const CATEGORY_STUDENT_DIFFICULTY_DISABILITY = 'RIC_HPC';
    const CATEGORY_STUDENT_ETHNICITY = 'RGC_S12';
    const CATEGORY_STUDENT_HEALTH_PROBLEM_INDICATOR = 'RIC_LLD';
    const CATEGORY_STUDENT_BKSB_FILE_SUBJECT = 'PGC_BKSB_FILE_SUBJECT';
    const CATEGORY_STUDENT_PRIOR_ATTAINMENT_LEVEL = 'RIC_PRA';
    const CATEGORY_STUDENT_GENDER_IDENTITY = 'PGC_GENDER_IDENTITY';
    #STUDENT SUPPORT
    const CATEGORY_STUDENT_SUPPORT_RECORD_CATEGORY = 'PGC_STUDENT_SUPPORT_RECORD_CATEGORY';
    const CATEGORY_STUDENT_SUPPORT_RECORD_TYPE = 'PGC_STUDENT_SUPPORT_RECORD_TYPE';
    const CATEGORY_STUDENT_SUPPORT_RECORD_CONTACTED_BY = 'PGC_STUDENT_SUPPORT_RECORD_CONTACTED_BY';
    #REFERENCE
    const CATEGORY_REFERENCE_LEARNER = 'RGC_ALT';
    const CATEGORY_REFERENCE_AWARDING_BODY = 'REC_AWARDING_BODY';
    const CATEGORY_REFERENCE_CANDIDATE_NUMBER = 'RCN_CANDIDATE_NUMBER';
    const CATEGORY_REFERENCE_COLLEGE_CENTRE = 'RCC_COLLEGE_CENTRE';
    #MARKETING
    const CATEGORY_MKT_COURSE_APPLY_METHOD = 'PGC_MKT_COURSE_APPLY_METHOD';
    const CATEGORY_MKT_COURSE_LEVEL = 'PGC_MKT_COURSE_LEVEL';
    const CATEGORY_MKT_COURSE_START = 'PGC_MKT_COURSE_START';
    const CATEGORY_MKT_COURSE_HE_MOS = 'PGC_MKT_COURSE_HE_MOS';
    const CATEGORY_MKT_COURSE_MOS = 'PGC_MKT_COURSE_MOS';
    const CATEGORY_MKT_COURSE_STATUS = 'PGC_MKT_COURSE_STATUS';
    const CATEGORY_MKT_COURSE_VISIBILITY = 'PGC_MKT_COURSE_VISIBILITY';
    const CATEGORY_MKT_PICKLIST = 'PGC_MKT_PICKLIST';
    const CATEGORY_MKT_ASSET = 'PGC_MKT_ASSET';
    #MSG
    const CATEGORY_MSG_PRIORITY = 'PGC_MSG_PRIORITY';
    const CATEGORY_MSG_STATUS = 'PGC_MSG_STATUS';
    const CATEGORY_MSG_SEND_METHOD = 'PGC_MSG_SEND_METHOD';
    #APPLICATIONS
    const CATEGORY_APPLICATION_COURSE_STATUS = 'PGC_APPLICATION_COURSE_STATUS';
    #PROVISION
    const CATEGORY_PROVISION_ASSOCIATION = 'RGC_XTR';
    const CATEGORY_PROVISION_DELIVERY_METHOD = 'RIC_DLM';
    const CATEGORY_PROVISION_DELIVERY_MODE = 'RIC_DEL';
    const CATEGORY_PROVISION_AIM_TYPE = 'RIC_AIM';
    const CATEGORY_PROVISION_SOURCE_OF_FUNDING = 'RIC_SOF';
    const CATEGORY_PROVISION_FUNDING_STREAM = 'RIC_FM';
    const CATEGORY_PROVISION_SHORT_CODE= 'RGC_SH';
    const CATEGORY_PROVISION_DATASET_FORMAT = 'RGC_A48';
    #ENROLMENT
    const CATEGORY_ENROLMENT_DATA_SET_FORMAT = 'RGC_EST';
    #REG
    const CATEGORY_REGISTER_INFORMED_ABSENCE_REPORTED_BY = 'PGC_REGISTER_INFORMED_ABSENCE_REPORTED_BY';
    const CATEGORY_REGISTER_INFORMED_ABSENCE_CATEGORY = 'PGC_REGISTER_INFORMED_ABSENCE_CATEGORY';
    const CATEGORY_REGISTER_DELIVERY_METHOD = 'PGC_REGISTER_DELIVERY_METHOD';
    #MOODLE
    const CATEGORY_MOODLE_MISC_GROUP = 'PGC_MOODLE_MISC_GROUP';
    #HARASSMENT
    const CATEGORY_HARASSMENT_NATURE = 'PGC_HARASSMENT_NATURE';
    const CATEGORY_HARASSMENT_LOCATION = 'PGC_HARASSMENT_LOCATION';
    const CATEGORY_HARASSMENT_INVOLVEMENT = 'PGC_HARASSMENT_INVOLVEMENT';
    const CATEGORY_HARASSMENT_ABUSE_TYPE = 'PGC_HARASSMENT_ABUSE_TYPE';
    #EDUCATIONAL VISIT
    const CATEGORY_EDUCATIONAL_VISIT_CATEGORY = 'PGC_EDUCATIONAL_VISIT_CATEGORY';
    const CATEGORY_EDUCATIONAL_VISIT_EXPENSE = 'PGC_EDUCATIONAL_VISIT_EXPENSE';
    #RESOURCE FEE
    const CATEGORY_RESOURCE_FEE_CATEGORY = 'PGC_RESOURCE_FEE_CATEGORY';
    #COUNTRY
    const CODE_COUNTRY_ENGLAND = 'XF';
    #OPERATIONAL RISK
    const CATEGORY_WAYS_OF_WORKING = 'PGC_WAYS_OF_WORKING';
    const CATEGORY_STRATEGIC_AIM = 'PGC_STRATEGIC_AIM';
    const CATEGORY_RISK = 'PGC_RISK';
    #EPA MANAGEMENT
    const CATEGORY_EPA_STATUS = 'PGC_EPA_STATUS';

    private $id;
    private $code;
    private $description;
    private $academicYear;
    private $position;
    private $groupLabel;
    private $category;
    private $createdOn;
    
    public function __construct($description, $category)
    {
        $this->description = $description;
        $this->category = $category;
        $this->createdOn = new DateTime();
    }
    
    public function assertCategory($category)
    {
        if ($category === $this->category) {
            return;
        }
        
        throw new Exception(sprintf(
            'Invalid category, expected "%s".',
            $category
        ));
    }
    
    public function getCreatedOn()
    {
        return $this->createdOn;
    }

    public function __toString()
    {
        return (string) $this->description;
    }
    
    public function getId()
    {
        return $this->id;
    }

    public function getCategory()
    {
        return $this->category;
    }
        
    public function getCode()
    {
        return $this->code;
    }

    public function getDescription()
    {
        return $this->description;
    }

    public function getAcademicYear()
    {
        return $this->academicYear;
    }

    public function getPosition()
    {
        return $this->position;
    }

    public function getGroupLabel()
    {
        return $this->groupLabel;
    }

    public function setCode($code)
    {
        $this->code = $code;
        return $this;
    }

    public function setDescription($description)
    {
        $this->description = $description;
        return $this;
    }

    public function setAcademicYear($academicYear)
    {
        $this->academicYear = $academicYear;
        return $this;
    }

    public function setPosition($position)
    {
        $this->position = $position;
        return $this;
    }

    public function setGroupLabel($groupLabel)
    {
        $this->groupLabel = $groupLabel;
        return $this;
    }
}
