<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' =>true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],

    Knp\Bundle\SnappyBundle\KnpSnappyBundle::class => ['all' => true],    
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle::class => ['all' => true],
    Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle::class => ['all' => true],
    Gregwar\CaptchaBundle\GregwarCaptchaBundle::class => ['all' =>true],

    Petroc\AuthTktBundle\PetrocAuthTktBundle::class => ['all' => true],
    Petroc\AccessBundle\PetrocAccessBundle::class => ['all' => true],
    Petroc\CoreBundle\PetrocCoreBundle::class => ['all' => true],

    Cis\HealthAndSafetyBundle\CisHealthAndSafetyBundle::class => ['all' => true],
    Cis\ExamBundle\CisExamBundle::class => ['all' => true],
    Cis\WesBundle\CisWesBundle::class => ['all' => true],
    Cis\UserBundle\CisUserBundle::class => ['all' => true],
    Cis\TaskBundle\CisTaskBundle::class => ['all' => true],
    Cis\AccessBundle\CisAccessBundle::class => ['all' => true],
    Cis\CmsBundle\CisCmsBundle::class => ['all' => true],
    Cis\CrmBundle\CisCrmBundle::class => ['all' => true],
    Cis\PaymentBundle\CisPaymentBundle::class => ['all' => true],
    Cis\MenuBundle\CisMenuBundle::class => ['all' => true],
    Cis\StaffBundle\CisStaffBundle::class => ['all' => true],
    Cis\StudentBundle\CisStudentBundle::class => ['all' => true],
    Cis\FileShareBundle\CisFileShareBundle::class => ['all' => true],
    Cis\LrsBundle\CisLrsBundle::class => ['all' => true],
    Cis\EmpoweringEnterpriseBundle\CisEmpoweringEnterpriseBundle::class => ['all' => true],
    Cis\StationeryBundle\CisStationeryBundle::class => ['all' => true],
    Cis\ParkingBundle\CisParkingBundle::class => ['all' => true],
    Cis\QarBundle\CisQarBundle::class => ['all' => true],
    Cis\FinanceBundle\CisFinanceBundle::class => ['all' => true],
    Cis\ApprenticeshipBundle\CisApprenticeshipBundle::class => ['all' => true],
    Cis\MarketingBundle\CisMarketingBundle::class => ['all' => true],
    Cis\EstatesBundle\CisEstatesBundle::class => ['all' => true],
    Cis\CustomReporterBundle\CisCustomReporterBundle::class => ['all' => true],
    Cis\MoodleBundle\CisMoodleBundle::class => ['all' => true],
    Cis\EnrolmentBundle\CisEnrolmentBundle::class => ['all' => true],
    Cis\PersonalRecordBundle\CisPersonalRecordBundle::class => ['all' => true],
    Cis\TravelBundle\CisTravelBundle::class => ['all' => true],
    Cis\FundingBundle\CisFundingBundle::class => ['all' => true],
    Cis\MessagingBundle\CisMessagingBundle::class => ['all' => true],
    Cis\DestinationBundle\CisDestinationBundle::class => ['all' => true],
    Cis\BusinessPlanningBundle\CisBusinessPlanningBundle::class => ['all' => true],
    Cis\ProvisionBundle\CisProvisionBundle::class => ['all' => true],
    Cis\RegisterBundle\CisRegisterBundle::class => ['all' => true],
    Cis\JobShopBundle\CisJobShopBundle::class => ['all' => true],    
    Cis\SupportBundle\CisSupportBundle::class => ['all' => true], 
    Cis\EducationalVisitBundle\CisEducationalVisitBundle::class => ['all' => true], 
    
    Cis\CollegeCalendarBundle\CisCollegeCalendarBundle::class => ['all' => true],    
    Cis\AppointmentsBundle\CisAppointmentsBundle::class => ['all' => true],    
    Cis\BookingsBundle\CisBookingsBundle::class => ['all' => true],   
    Cis\LearningAimBundle\CisLearningAimBundle::class => ['all' => true], 
    Cis\SelfAssessmentBundle\CisSelfAssessmentBundle::class => ['all' => true],
    Cis\LaptopCabinetBundle\CisLaptopCabinetBundle::class => ['all' => true],
    Cis\ReportingBundle\CisReportingBundle::class => ['all' => true],
    Cis\ApplicationsBundle\CisApplicationsBundle::class => ['all' => true],
    Cis\ProgressTrackingBundle\CisProgressTrackingBundle::class => ['all' => true],
    Cis\OperationalRiskBundle\CisOperationalRiskBundle::class => ['all' => true],
    Cis\LearnerInclusionPlanBundle\CisLearnerInclusionPlanBundle::class => ['all' => true],
    Cis\AutoWithdrawalBundle\CisAutoWithdrawalBundle::class => ['all' => true],
    Cis\StrategicRiskBundle\CisStrategicRiskBundle::class => ['all' => true],
    Cis\ActionImprovementPlanBundle\CisActionImprovementPlanBundle::class => ['all' => true],
    Cis\CovidBundle\CisCovidBundle::class => ['all' => true],
    Cis\ExperienceWorksBundle\CisExperienceWorksBundle::class => ['all' => true],
    Cis\ProspectusBundle\CisProspectusBundle::class => ['all' => true],
    Cis\HigherEducationBundle\CisHigherEducationBundle::class => ['all' => true],
    Cis\ResourceFeeBundle\CisResourceFeeBundle::class => ['all' => true],
    Cis\DlsfBundle\CisDlsfBundle::class => ['all' => true],
];
